http:
  middlewares:
    compress:
      compress: {}

    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "SAMEORIGIN" #"DENY"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "strict-origin"
          Content-Security-Policy: "default-src 'self'; script-src 'self'; object-src 'self'; frame-ancestors 'none';"

    crowdsec:
      plugin:
        bouncer:
          CrowdsecLapiKey: "replace-me"
          Enabled: "true"
          loglevel: "DEBUG"
          crowdsecappsecenabled: "true"
          crowdsecappsechost: "crowdsec:7422"
          crowdsecmode: "stream"

tls:
  options:
    default:
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13