http:
  middlewares:
    compress:
      compress: {}

    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "no-referrer-when-downgrade"
          Content-Security-Policy: "default-src 'self'; script-src 'self'; object-src 'none';"

    crowdsec:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: "replace-me"
          Enabled: "false"
