services:
  adminer:
    image: adminer
    container_name: "adminer"
    restart: unless-stopped
    environment:
      - TZ 
      - ADMINER_DEFAULT_SERVER=postgres 
    labels:
      - traefik.enable=true
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=web,websecure
      - traefik.http.routers.adminer.tls=true
      - traefik.http.routers.adminer.tls.certresolver=letsencrypt
      - traefik.docker.network=proxy_default
      - traefik.http.routers.adminer.rule=Host(`${DOMAIN_NAME}`) && ( PathPrefix(`/acessodb`) )
      - homepage.group=Database
      - homepage.name=adminer
      - homepage.icon=adminer
      - homepage.href=http://adminer:8080
      - homepage.description=DB client 
    networks: 
      - proxy_default
      - db 




