services:
  adminer:
    image: adminer
    container_name: "adminer"
    restart: unless-stopped
    environment:
      - TZ 
      - ADMINER_DEFAULT_SERVER=postgres 
    labels:
      - homepage.group=Database
      - homepage.name=adminer
      - homepage.icon=adminer
      - homepage.href=http://adminer.local:8080
      - homepage.description=DB client 
    networks: 
      - local
      - db 




