---
services:
  dns:
    image: dockurr/dnsmasq:latest 
    container_name: dns
    environment:
      - DNS1=127.0.0.11 # DNS interno do Docker
      - DNS2=10.0.0.20   # Seu outro servidor DNS
    command: --server=/local/127.0.0.11 --log-queries --log-facility=-
    networks:
      local:
        ipv4_address: 192.168.180.254
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "nslookup", "-timeout=2", "google.com"]
      interval: 5m
      timeout: 10s
      retries: 3
    labels:
      - homepage.group=Network
      - homepage.name=DNS Server
      - homepage.icon=dns
      - homepage.description=dnsmasq