---
services:
  dns:
    image: dockurr/dnsmasq
    container_name: dns
    command: -k -S /local/127.0.0.11 --dhcp-option=option:dns-server,127.0.0.1
    #ports:      - "53:53/udp"
    networks:
      - proxy_default
      - local
    restart: always