services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - local
    labels:
      homepage.group: system
      homepage.name: "Dozzle"
      homepage.icon: "docker.png"
      homepage.href: "http://dozzle.local:8080"
      homepage.description: "Logs"
