
services:


  acessoweb:
    image: filebrowser/filebrowser
    container_name: acessoweb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
    volumes:
      - ${VOL_FILEBROWSER}/database/database.db:/database.db
      #- ${VOL_FILEBROWSER}/database/filebrowser.json:/config/settings.json
      - /opt/files:/srv
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.services.file.loadbalancer.server.port=80
      - traefik.http.routers.file.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=http,https
      - traefik.http.routers.file.rule=Host(`${NOIP_URL1}`) && PathPrefix(`/acessoweb`) 
    networks:
      - proxy_default
