services:
  gemini-cli-web:
    image: marcoslkz/gemini-cli-ui
    container_name: gemini-cli-web
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Add your API key to the .env file
    volumes:
      - gemini_data:/app/data
    networks:
      - proxy_default
      - local
    labels:
      - "homepage.group=AI"
      - "homepage.name=Gemini Web"
      - "homepage.icon=gemini"
      - "homepage.href=https://gemini.${ROOT_DOMAIN}"
      - "homepage.description=Gemini CLI Web Interface"

volumes:
  gemini_data:
    driver_opts:
      type: none
      device: "${VOL_GEMINI}"
      o: bind
