services:
  gemini:
    image: marcoslkz/gemini-cli-ui
    container_name: gemini
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GEMINI_API_KEY
    volumes:
      - gemini_data:/app/data
    networks:
      - proxy_default
      - local
    labels:
      - "homepage.group=AI"
      - "homepage.name=Gemini Web"
      - "homepage.icon=gemini"
      - "homepage.href=http://gemini.local:4008"
      - "homepage.description=Gemini CLI Web Interface"

volumes:
  gemini_data:
    driver_opts:
      type: none
      device: /opt/files/gemini
      o: bind
