services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    volumes:
      - $VOL_HOMEPAGE:/app/config
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      PUID: $PUID
      PGID: $PGID
    networks:
      - local
      - sec
    restart: unless-stopped # Garante que o serviço reinicie automaticamente
    healthcheck: # Opcional, mas recomendado
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      - homepage.group=System
      - homepage.name=Homepage
      - homepage.icon=homepage
      - homepage.href=http://homepage.local:3000
      - homepage.description=Tools
