services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    #ports:    - 3000:3000
    volumes:
      - $VOL_HOMEPAGE:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${NOIP_URL1}
      PUID: $PUID
      PGID: $PGID
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.frontend.entryPoints=web,websecure
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt
      - traefik.http.routers.keycloak.rule=Host(`${NOIP_URL1}`) && PathPrefix(`/gerencia`)
      #- traefik.http.services.keycloak.loadbalancer.server.port=3000
      #- traefik.http.services.keycloak.loadbalancer.server.scheme=https
      #- traefik.http.services.keycloak.loadbalancer.serversTransport=mytransport@file
