services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    volumes:
      - $VOL_HOMEPAGE:/app/config
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      PUID: $PUID
      PGID: $PGID
    networks:
      - local
      - sec
    restart: unless-stopped 
    labels:
      - homepage.group=System
      - homepage.name=Homepage
      - homepage.icon=homepage
      - homepage.href=http://homepage.local:3000
      - homepage.description=Tools
