services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    #ports:    - 3000:3000
    volumes:
      - $VOL_HOMEPAGE:/app/config 
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      PUID: $PUID
      PGID: $PGID
    networks: 
      - local
