services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    #ports:    - 3000:3000
    volumes:
      - $VOL_HOMEPAGE:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN_NAME}
      PUID: $PUID
      PGID: $PGID
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.frontend.entryPoints=web,websecure
      - traefik.http.routers.${COMPOSE_FILE}.tls=true
      - traefik.http.routers.${COMPOSE_FILE}.tls.certresolver=letsencrypt
      - traefik.http.routers.${COMPOSE_FILE}.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/gerencia`)
      #- traefik.http.services.${COMPOSE_FILE}.loadbalancer.server.port=3000
      #- traefik.http.services.${COMPOSE_FILE}.loadbalancer.server.scheme=https
      #- traefik.http.services.${COMPOSE_FILE}.loadbalancer.serversTransport=mytransport@file
