services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak_web
    environment:
      KC_DB: postgres 
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: https://${NOIP_URL2}
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_PROXY_HEADERS: forwarded

    entrypoint:
      - /bin/sh
      - -c
    command:
      - "/opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.frontend.entryPoints=web,websecure
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt
      - traefik.http.routers.keycloak.rule=Host(`${NOIP_URL2}`) #&& PathPrefix(`/admin`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      #- traefik.http.services.keycloak.loadbalancer.server.scheme=https
      #- traefik.http.services.keycloak.loadbalancer.serversTransport=mytransport@file
      - homepage.group=System
      - homepage.name=keycloak
      - homepage.icon=keycloak
      - homepage.href=https://${NOIP_URL2}
      - homepage.description=Auth 
    networks: 
      - local
      - proxy_default
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  keycloak_data:

