services:
  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DISCORD_WEBHOOK_ID=${DISCORD_WEBHOOK_ID}
      - DISCORD_KEY=${DISCORD_KEY}
    entrypoint: >-
      sh -c "
      cat <<EOF >/etc/mailrise.conf
\"discord@local\":
  urls:
    - \"discord://\${DISCORD_WEBHOOK_ID}/\${DISCORD_KEY}\"
EOF
      exec /usr/local/bin/mailrise
      "
    ports:
      - "8025:8025"
    networks:
      - mail
