services:
  webserver:
    image: gitlab.cecierj.edu.br:5050/depr/dockerfile/moodle:php8.3
    container_name: "moodle"
    restart: unless-stopped
    environment:
      - TZ
      - SITE_PATH
      - ADMIN_USER
      - ADMIN_PASS
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=postgres
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_NAME=${POSTGRES_DB}
      - MOODLE_DATABASE_USER=${POSTGRES_USER}
      - MOODLE_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DOMAIN_URL=${SITE_PATH}.${ROOT_DOMAIN}
      - MOODLE_HOST=${SITE_PATH}.${ROOT_DOMAIN}
      - MOODLEDATA=/var/www/moodledata
      - MOODLE_SKIP_BOOTSTRAP=yes
      - MOODLE_SSLPROXY=true
      - MOODLE_USERNAME=${ADMIN_USER}
      - MOODLE_PASSWORD=${ADMIN_PASS}
      - MOODLE_EMAIL=${MAILMANAGER}
      - MOODLE_LANG=pt_br
      - BITNAMI_DEBUG=true
      - DEBUG=true
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.services.moodle.loadbalancer.server.port=443
      - traefik.http.services.moodle.loadbalancer.server.scheme=https
      - traefik.http.services.moodle.loadbalancer.serverstransport=selfsigned@file
      - traefik.http.routers.moodle.tls.certresolver=letsencrypt
      - traefik.http.routers.moodle.tls=true
      - traefik.frontend.entryPoints=http,https
      - traefik.http.routers.moodle.rule=Host(`${SITE_PATH}.${ROOT_DOMAIN}`)
      - traefik.http.routers.moodle.middlewares=security-headers@file
    volumes:
      - ${MOODLEDATA}:/var/www/moodledata
      - ${MOODLESRC}:/var/www/html
    networks:
      - proxy_default

