services:
  moodle:
    image: erseco/alpine-moodle
    container_name: moodle
    restart: unless-stopped
    environment:
      - TZ
      - SITE_PATH
      - ADMIN_USER
      - ADMIN_PASS
      - LANG=pt_BR.UTF-8
      - LANGUAGE=pt_BR
      - MOODLE_SSLPROXY=true
      - MOODLE_USERNAME=${ADMIN_USER}
      - MOODLE_PASSWORD=${ADMIN_PASS}
      - MOODLE_EMAIL=${MAILMANAGER}
      - MOODLE_LANG=pt_br
      - SITE_URL=https://app.$DOMAIN_NAME
      - REVERSEPROXY=false
      - SSLPROXY=true
      - REDIS_HOST=cache
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      #- DB_FETCHBUFFERSIZE=
      #- DB_DBHANDLEOPTIONS=false
      #- DB_HOST_REPLICA=
      #- DB_PORT_REPLICA=
      #- DB_USER_REPLICA=
      #- DB_PASS_REPLICA=
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=postgres
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_NAME=${POSTGRES_DB}
      - MOODLE_DATABASE_USER=${POSTGRES_USER}
      - MOODLE_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PREFIX=app_
      #- MY_CERTIFICATES=none
      - MOODLE_LANGUAGE=br
      - MOODLE_SITENAME=Studio Magleides
      - SMTP_HOST=mailrise.local
      - SMTP_PORT=8025
      #- SMTP_USER
      #- SMTP_PASSWORD
      #- SMTP_PROTOCOL
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@${ROOT_DOMAIN}
      - MOODLE_MAIL_PREFIX=[PILATES]
      - AUTO_UPDATE_MOODLE=true
      - DEBUG=false
      - client_max_body_size=50M
      - post_max_size=50M
      - upload_max_filesize=50M
      - max_input_vars=5000
      #- PRE_CONFIGURE_COMMANDS=
      #- POST_CONFIGURE_COMMANDS=
      - RUN_CRON_TASKS=true

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.services.moodle.loadbalancer.server.port=443
      - traefik.http.services.moodle.loadbalancer.server.scheme=https
      - traefik.http.services.moodle.loadbalancer.serverstransport=selfsigned@file
      - traefik.http.routers.moodle.tls.certresolver=letsencrypt
      - traefik.http.routers.moodle.tls=true
      - traefik.frontend.entryPoints=http,https
      - traefik.http.routers.moodle.rule=Host(`${SITE_PATH}.${ROOT_DOMAIN}`)
      - traefik.http.routers.moodle.middlewares=security-headers@file
    volumes:
      - ${MOODLEDATA}:/var/www/moodledata
      - ${MOODLESRC}:/var/www/html
    networks:
      - proxy_default
    networks:
      - cache
      - proxy_default
