
services:
  noip-duc:
    image: ghcr.io/noipcom/noip-duc
    container_name: noip-duc
    restart: unless-stopped
    read_only: true 
    cap_drop: 
      - ALL
    healthcheck: 
      test: ["CMD-SHELL", "pgrep noip-duc || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 3
    environment:
      - NOIP_USERNAME
      - NOIP_PASSWORD
      - NOIP_HOSTNAMES=${NOIP_URL1},${NOIP_URL2},${NOIP_URL3}
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
    labels:
      homepage.group: System
      homepage.name: "No-IP DUC"
      homepage.icon: "mdi-dns"
      homepage.href: "https://www.noip.com/"
      homepage.description: "DDNS No-IP"




