services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - TZ
      - DOMAIN_NAME
      - SITE_PATH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - homepage.group=System
      - homepage.name=portainer
      - homepage.icon=portainer
      - homepage.href=http://portainer:80
      - homepage.description=Docker manager 
    networks: 
      - local
      
volumes:
  portainer_data:
    driver_opts:
      type: none
      device: ${VOL_PORTAINER}
      o: bind
