services:
  portainer:
    image: portainer/portainer-ee:lts
    container_name: portainer
    restart: unless-stopped
    environment:
      - TZ
      - DOMAIN_NAME
      - SITE_PATH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - homepage.group=System
      - homepage.name=Portainer
      - homepage.icon=portainer
      - homepage.href=https://portainer:9443
      - homepage.description=Docker manager 
      - homepage.widget.type=portainer
      - homepage.widget.url=http://portainer:9000
      - homepage.widget.key=${PORTAINER_TOKEN}
      - homepage.widget.env=1
      - homepage.widget.kubernetes=false
    networks: 
      - local
      
volumes:
  portainer_data:
    driver_opts:
      type: none
      device: ${VOL_PORTAINER}
      o: bind
