
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
    labels:
      - homepage.group=Database
      - homepage.name=postgres
      - homepage.icon=postgres
      - homepage.href=http://adminer:8080
      - homepage.description=Database local 
    networks: 
      - db
      - local

volumes:
  postgres_storage:
    driver_opts:
      type: none
      device: ${VOL_POSTGRES}
      o: bind
