
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    networks:
      - db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']

volumes:
  postgres_storage:
    driver_opts:
      type: none
      device: ${VOL_POSTGRES}
      o: bind
