services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    mem_limit: 5gb
    networks:
    - cache
    healthcheck:
      test: redis-cli ping
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
    - homepage.group=Database
    - homepage.name=Redis
    - homepage.icon=redis
    - homepage.description=In-memory data store
