
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ
      - WATCHTOWER_LOG_LEVEL=warn
      #- DOCKER_HOST=tcp://dockerproxy:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3000
