
services:
  wg-easy:
    environment:
    #  Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
    #  - INSECURE=false
    #  - PASSWORD=uma_senha_forte
      - WG_HOST=${DOMAIN_NAME}
      - WG_PORT=51820
      - WG_DEFAULT_DNS=192.168.180.254
      - WG_ALLOWED_IPS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    networks:
      local:
    volumes:
      - ${VOL_PROXY}/wg:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    labels:
      homepage.group: "System"
      homepage.name: "WireGuard"
      homepage.icon: "wireguard"
      homepage.href: "http://wg-easy:51821"
      homepage.description: "WireGuard (wg-easy)"
      homepage.widget.type: wgeasy
      homepage.widget.url: http://wg-easy:51821
      homepage.widget.version: 2
      homepage.widget.threshold: 2