services:
  wger-server:
    image: wger/server
    command: gunicorn wger.wsgi:application --bind 0.0.0.0:8000 --workers 4
    container_name: wger
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WGER_URL_PREFIX=/studio
      - DJANGO_SECRET_KEY=${WGER_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=app.${ROOT_DOMAIN},wger.local
      - CSRF_TRUSTED_ORIGINS=https://app.${ROOT_DOMAIN},wger.local
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_USER=${POSTGRES_USER}
      - DJANGO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_DB_DATABASE=wger
      - DJANGO_REDIS_HOST=redis
      - DJANGO_REDIS_PORT=6379
      - SITE_OWNER_EMAIL=${MAILMANAGER}
      - SITE_OWNER_PASSWORD=${WGER_ADMIN_PASSWORD}
      - SITE_OWNER_USERNAME=wger-admin
      #- DJANGO_DEFAULT_FILE_STORAGE=storages.backends.s3boto3.S3Boto3Storage
      #- DJANGO_STATICFILES_STORAGE=storages.backends.s3boto3.S3Boto3Storage
      #- AWS_S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      #- AWS_S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      #- AWS_STORAGE_BUCKET_NAME=AWS_STATIC_BUCKET_NAME:-local/wger-static
      #- AWS_S3_ENDPOINT_URL=http://minio:9000
      #- AWS_S3_OBJECT_PARAMETERS={"CacheControl":"max-age=86400"}
      #- AWS_LOCATION=local
      #- AWS_STATIC_BUCKET_NAME=${AWS_STATIC_BUCKET_NAME:-local/wger-static}
      ##- AWS_MEDIA_BUCKET_NAME=${AWS_MEDIA_BUCKET_NAME:-local/wger-media}
      #- AWS_S3_SECURE_URLS = False # Use False if not using HTTPS with MinIO 
      #- STATIC_URL = "/static/" # Default Django static URL 
      #- STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
      #- MEDIA_URL = "/media/" 
      #- DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
      #- STATIC_URL=https://${ROOT_DOMAIN}/studio/static/
      #- MEDIA_URL=https://${ROOT_DOMAIN}/studio/media/
      #STATICFILES_DIRS = [BASE_DIR / "static"]
      #STATIC_ROOT = BASE_DIR / "assets" # For collectstatic
    volumes:
      - /opt/files/static/static:/home/wger/static
      - /opt/files/static/media:/home/wger/media
    networks:
      - proxy_default
      - db
      - cache
      - local
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.routers.wger.rule=Host(`app.${ROOT_DOMAIN}`) # && PathPrefix(`/studio`)
      - traefik.http.routers.wger.middlewares=wger-stripprefix@docker
      - traefik.http.middlewares.wger-stripprefix.stripprefix.prefixes=/studio
      - traefik.http.routers.wger.entrypoints=websecure
      - traefik.http.routers.wger.tls.certresolver=letsencrypt
      - traefik.http.services.wger.loadbalancer.server.port=8000
      - homepage.group=Health
      - homepage.name=Wger (Pilates)
      - homepage.icon=dumbbell
      - homepage.href=http://wger.local:8000/studio
      - homepage.description=Workout Manager
