services:
  wger-server:
    image: wger/server
    container_name: wger-server
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WGER_URL_PREFIX=/studio
      - DJANGO_SECRET_KEY=${WGER_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN_NAME}
      - CSRF_TRUSTED_ORIGINS=https://${ROOT_DOMAIN}
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_USER=${POSTGRES_USER}
      - DJANGO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_DB_NAME=wger
      - DJANGO_REDIS_HOST=redis
      - DJANGO_REDIS_PORT=6379
      - SITE_OWNER_EMAIL=${MAILMANAGER}
      - SITE_OWNER_PASSWORD=${WGER_ADMIN_PASSWORD}
      - SITE_OWNER_USERNAME=wger-admin
    volumes:
      - wger_static:/home/wger/static
      - wger_media:/home/wger/media
    networks:
      - proxy_default
      - db
      - cache
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.routers.wger.rule=Host(`${ROOT_DOMAIN}`) && PathPrefix(`/studio`)
      - traefik.http.routers.wger.middlewares=wger-stripprefix@docker
      - traefik.http.middlewares.wger-stripprefix.stripprefix.prefixes=/studio
      - traefik.http.routers.wger.entrypoints=websecure
      - traefik.http.routers.wger.tls.certresolver=letsencrypt
      - traefik.http.services.wger.loadbalancer.server.port=8000
      - homepage.group=Health
      - homepage.name=Wger (Pilates)
      - homepage.icon=dumbbell
      - homepage.href=http://wger.local:8000/studio
      - homepage.description=Workout Manager

volumes:
  wger_static:
    driver_opts:
      type: none
      device: ${VOL_PROXY}/wger/static
      o: bind
  wger_media:
    driver_opts:
      type: none
      device: ${VOL_PROXY}/wger/media
      o: bind
