name: Update Docker Secret from Vaultwarden

on:
  workflow_dispatch:
    inputs:
      secret_names:
        description: 'Space-separated list of secret names to update (e.g., "gemini_env_file wger_env_file").'
        required: true
        default: 'gemini_env_file'

jobs:
  update-secret:
    name: Fetch Attachment and Update Docker Secret
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Update Script
        env:
          VW_URL: "https://${{ secrets.NOIP_URL3 }}"
          VW_CLIENT_ID: ${{ secrets.VW_CLIENT_ID }}
          VW_CLIENT_SECRET: ${{ secrets.VW_CLIENT_SECRET }}
        run: |
          echo "Ensuring script is executable..."
          chmod +x ./scripts/update_gemini_secret.sh
          
          echo "Running script to update Docker secret(s)..."
          ./scripts/update_gemini_secret.sh "${{ github.event.inputs.secret_names }}"
